import os

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
AMQP_PORT = int(os.getenv('AMQP_PORT',"5672"))
RABBITMQ_USER = os.getenv('RABBITMQ_USER')
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')
EXCHANGE_NAME = os.getenv('EXCHANGE_NAME')
QUEUE_NAME = os.getenv('QUEUE_NAME')
DEAD_LETTER_EXCHANGE_NAME = os.getenv('DEAD_LETTER_EXCHANGE_NAME')
DEAD_LETTER_QUEUE_NAME = os.getenv('DEAD_LETTER_QUEUE_NAME')
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST')
ELASTICSEARCH_CONNECTION = True if os.getenv('ELASTICSEARCH_CONNECTION') == "True" else False
ELASTICSEARCH_PORT = int(os.getenv('ELASTICSEARCH_PORT'))
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = int(os.getenv('DATABASE_PORT',"5432"))
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USERNAME = os.getenv('DATABASE_USERNAME')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
threadPoolExecuteWorker = 1