from enum import Enum,auto

class ActionType(Enum):
    completed = 'COMPLETED'
    started = 'STARTED'
    continuous = 'CONTINUOUS'
    error = 'ERROR'
    create_user_completed = 'CREATE_USER_COMPLETED'
    create_user_error = 'CREATE_USER_ERROR'
    set_permission_completed = 'SET_PERMISSION_COMPLETED'
    set_permission_error = 'SET_PERMISSION_ERROR'
    set_topic_permission_completed = 'SET_TOPIC_PERMISSION_COMPLETED'
    set_topic_permission_error = 'SET_TOPIC_PERMISSION_ERROR'
    user_recognition_completed = 'USER_RECOGNITION_COMPLETED'
    user_recognition_error = 'USER_RECOGNITION_ERROR'
    old_user_delete_completed = 'OLD_USER_DELETE_COMPLETED'
    old_user_delete_error = 'OLD_USER_DELETE_ERROR'
    user_delete_completed = 'USER_DELETE_COMPLETED'
    user_delete_error = 'USER_DELETE_ERROR'
    topic_remove_started = 'TOPIC_REMOVE_STARTED'
    topic_remove_completed = 'TOPIC_REMOVE_COMPLETED'
    topic_remove_error = 'TOPIC_REMOVE_ERROR'
    topic_remove_not_found = 'TOPIC_REMOVE_NOT_FOUND'
    listen_topic_completed = 'LISTEN_TOPIC_COMPLETED'
    listen_topic_error = 'LISTEN_TOPIC_ERROR'
    same_topic_listen_error = 'SAME_TOPIC_LISTEN_ERROR'
    test_topic_listen_completed = 'TEST_TOPIC_LISTEN_COMPLETED'
    close_listen_topic_completed = 'CLOSE_LISTEN_TOPIC_COMPLETED'
    close_listen_topic_not_found = 'CLOSE_LISTEN_TOPIC_NOT_FOUND'